import type { Metadata } from "next";
import clsx from "clsx";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Next E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "bg-slate-700")}
      >
        <Navbar />
        <main className="min-h-screen bg-gradient-to-br from-orange-700 via-pink-700 to-purple-900 p-18">
        {children}
        </main>
      </body>
    </html>
  );
}
